services:
  sync:
    container_name: cp-sync
    image: ghcr.io/wsj-br/cursorpace-syncserver:latest
    build: .
    ports: ["7050:7050"]
    volumes:
      - cp-sync-data:/data
volumes:
  cp-sync-data:
